name: Sequential ETL Jobs with Spark

on:
  #schedule:
  #  - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Java (required for Spark)
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jdk

    - name: Install Spark
      run: |
        sudo apt-get install -y spark

    - name: bronze_ticker_data
      run: |
        python bronze_ticker_data.py
  
    - name: bronze_sp500_tickers
      run: |
        python bronze_sp500_tickers.py

    - name: silver_currency_data
      run: |
        python silver_currency_data.py
  
    - name: gold_main_sp500
      run: |
        python gold_main_sp500.py
