name: Sequential ETL Jobs with Spark

on:
  #schedule:
  #  - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8.19
      uses: actions/setup-python@v3
      with:
        python-version: '3.8.19'

    - name: Install dependencies
      run: |
        pip install --force-reinstall -r requirements.txt

    - name: Install Java (required for Spark)
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jdk

    - name: Install Spark
      run: |
        # Download the Spark package from GitHub Releases
        wget https://github.com/cmatoses/financialkeepcoders/releases/tag/spark
        tar xvf spark-3.5.2-bin-hadoop3.tgz
        echo "$(pwd)/spark-3.5.2-bin-hadoop3/bin" >> $GITHUB_PATH
        
    - name: bronze_ticker_data
      run: |
        python bronze_ticker_data.py
  
    - name: bronze_sp500_tickers
      run: |
        python bronze_sp500_tickers.py

    - name: silver_currency_data
      run: |
        python silver_currency_data.py
  
    - name: gold_main_sp500
      run: |
        python gold_main_sp500.py
