name: Python Package using Conda

on:
    workflow_dispatch:


jobs:
  build-linux:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.8
        auto-activate-base: false

    - name: Add conda to system path
      run: |
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

    - name: Update conda environment
      run: |
        conda env update --file environment.yml --name base
        conda activate base
      
    - name: Run bronze_ticker_data
      run: |
        python financialkeepcoders/bronze_ticker_data.ipynb
  
    - name: Run bronze_sp500_tickers
      run: |
        python financialkeepcoders/bronze_sp500_tickers.ipynb

    - name: Run silver_currency_data
      run: |
        python financialkeepcoders/silver_currency_data.ipynb
  
    - name: Run gold_main_sp500
      run: |
        python financialkeepcoders/gold_main_sp500.ipynb
